services:
  forkiteh-tron:
    container_name: forkiteh-tron
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/core.env
    ports:
      - "8060:8000"
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres

  postgres:
    container_name: forkiteh-postgres
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - env/postgres.env
    ports:
      - '5432:5432'


volumes:
  postgres_data:
